### ISSUE TITLE
Allow additions to UA String

### ISSUE THREAD

**Issue by fiveisprime** [lostintangent/az-login#2]
The `ms-rest-azure` module exposes a method called `addUserAgentInfo` that allows appending data to the UA String. This should be used and exposed by az-login.

I'm thinking it should default to

```js
const pkg = require('./package.json')
azure.addUserAgentInfo(`${pkg.name}/${pkg.version}`)
```

But also expose this so tools that are using az-login (asjs and serverless) can add their own UA strings. Probably just one of these.. even though it's ugly, I don't know a better way.

```js
exports.addUserAgentInfo = azure.addUserAgentInfo
```

Once updated both here and in the serverless plugin, this will add `az-login/0.1.6 serverless-azure-functions/0.1.2` so we can query for usage. :)

**Comment by lostintangent** [comment]
Awesome idea! I'll make sure to add this before we merge the support in Serverless, so that we can track it.

**Comment by lostintangent** [comment]
@fiveisprime Are you sure that the `ms-rest-azure` module exports an `addUserAgentInfo` method? I tried calling it and it doesn't seem to exist. That said, I see this method on all of the actual client APIs.

**Comment by fiveisprime** [comment]
Well damn, I think it's a member method of `ServiceClient` and only available on an instantiated client object.

So you would instantiate a service client (e.g. storage), then update the UA string for that client for requests that it makes.

I'll think about this and come up with a way to make it work. :)

**Comment by lostintangent** [comment]
OK cool, thanks dude!

**Comment by fiveisprime** [comment]
This doesn't need to be in this module.. I'll update azjs and serverless instead. :)
