### ISSUE TITLE
Auto-opening Web browser may hide instructions

### ISSUE THREAD

**Issue by vjrantal** [lostintangent/az-login#3]
When trying out https://github.com/serverless/serverless-azure-functions/pull/63 (awesome work by the way!!) I felt that for a user new to the Azure Device Login experience, it might not be clear what to do after the Web browser is opened. This is because auto-opening the browser window hides the instructions printed to the console, i.e., it hides this message:

```
$ serverless deploy
Serverless: Packaging service...
Serverless: Logging in to Azure
Serverless: Paste this code (copied to your clipboard) into the launched browser, and complete the authentication process: 1234
```

Instead of above instructions, user sees a Web page with following:

<img width="379" alt="screen shot 2017-05-03 at 9 59 17" src="https://cloud.githubusercontent.com/assets/207474/25650671/3897dce4-2fe7-11e7-8651-dd17587161e5.png">

However, it isn't obvious that the code is currently in user's clipboard and should be pasted into this field.

In my opinion, a better default user experience might be the way `az login` works, which is something like:

```
$ az login
To sign in, use a web browser to open the page https://aka.ms/devicelogin and enter the code 1234 to authenticate.
```

This would also allow the user to choose which browser to use, for example, in my case I didn't want to use the system default Web browser since that wasn't the one in which I was signed in as the user I wanted to use with `serverless deploy`.

**Comment by lostintangent** [comment]
This module now prints out the URL and code needed to perform the login process, in addition to copying the code to the clipboard and launching the default browser. 

If it would be valuable, we could definitely also make it an option to prevent automatically launching a browser, in case consuming apps (e.g. Serverless) wanted to disable that behavior.

**Comment by fiveisprime** [comment]
Would it help to add a short delay before opening the browser?

**Comment by vjrantal** [comment]
@fiveisprime Short delay might help since then you might be able to read the instructions during that delay. However, is auto-opening the browser really required? For typical users, the login doesn't happen that often - perhaps only in the first-use scenario. It is the first-use scenario where reading the instructions is required since then, user doesn't yet know what to do within the Web browser.

**Comment by fiveisprime** [comment]
@lostintangent I like the idea of making it an option.

I was starting to write up that launching the browser was part of what made this module different from the node SDK's interactive login, but the SP storing logic makes it much more powerful really. Being able to turn the auto-launch off makes sense to keep this code as usable as possible.

**Comment by lostintangent** [comment]
I'm going to close this issue based on two updates that have been published:

1. The default Interactive login message now displays the URL and code, so as to not rely on the auto-launching behavior (e.g. when running this lib in a Docker container)

2. There is a new login option to disable the auto-launch behavior. It's still true by default, but consuming tools can disable if easily now.

Let me know if you have any other feedback here! I'll also send out a PR to the Serverless Azure plugin that uses the latest version and this lib.

Thanks!
